import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header/Header.jsx";
import Navbar from "../components/Navbar/Navbar.jsx";
//import styles from "../styles/globals.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      {/** Navbar component  */}
      <Navbar />
      {/** Results component */}
    </div>
  );
}
